// frontend/src/components/ui/BaseTable.vue
<template>
  <div class="table-wrapper">
    <div v-if="loading" class="table-loading">
      <div v-for="i in 5" :key="i" class="skeleton" style="height:40px;margin:.5rem 1rem" />
    </div>
    <template v-else>
      <div v-if="!rows.length" class="table-empty">
        <span>لا توجد بيانات</span>
      </div>
      <table v-else>
        <thead>
          <tr>
            <th v-for="col in columns" :key="col.key">{{ col.label }}</th>
            <th v-if="$slots.actions">إجراءات</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in rows" :key="row.id ?? row">
            <td v-for="col in columns" :key="col.key">
              <slot :name="`cell-${col.key}`" :row="row" :value="row[col.key]">
                {{ row[col.key] ?? '—' }}
              </slot>
            </td>
            <td v-if="$slots.actions">
              <slot name="actions" :row="row" />
            </td>
          </tr>
        </tbody>
      </table>
    </template>
  </div>
</template>

<script setup>
defineProps({
  columns: { type: Array,   required: true },
  rows:    { type: Array,   default: () => [] },
  loading: { type: Boolean, default: false },
})
</script>

<style scoped>
.table-loading { padding: .5rem; }
.table-empty   {
  text-align: center;
  padding: 3rem;
  color: var(--color-text-muted);
  font-size: .9rem;
}
</style>

// frontend/src/components/ui/BaseTable.jsx
import './BaseTable.css'

export default function BaseTable({ columns, rows = [], loading = false, renderCell = {}, renderActions }) {
  if (loading) {
    return (
      <div className="table-wrapper">
        <div className="table-loading">
          {[1, 2, 3, 4, 5].map(i => (
            <div key={i} className="skeleton" style={{ height: 40, margin: '.5rem 1rem' }} />
          ))}
        </div>
      </div>
    )
  }

  if (!rows.length) {
    return (
      <div className="table-wrapper">
        <div className="table-empty"><span>لا توجد بيانات</span></div>
      </div>
    )
  }

  return (
    <div className="table-wrapper">
      <table>
        <thead>
          <tr>
            {columns.map(col => (
              <th key={col.key}>{col.label}</th>
            ))}
            {renderActions && <th>إجراءات</th>}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, rowIdx) => (
            <tr key={row.id ?? rowIdx}>
              {columns.map(col => (
                <td key={col.key}>
                  {renderCell[col.key]
                    ? renderCell[col.key]({ row, value: row[col.key] })
                    : (row[col.key] ?? '—')}
                </td>
              ))}
              {renderActions && (
                <td>{renderActions({ row })}</td>
              )}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
